// Q7
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'

// Q11
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME ASC, DATETIME DESC;

// Q12
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NAME LIKE '%EL%' AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME

// Q13
SELECT COUNT(*) as USERS
FROM USER_INFO
WHERE AGE IS NULL

// Q14
SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCT

// Q15
SELECT ANIMAL_TYPE, coalesce(NAME, "No name") AS NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS

// Q18
SELECT ANIMAL_ID, NAME, SUBSTRING(DATETIME,1,10) AS 날짜
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

// Q19
SELECT DR_NAME, DR_ID, MCDP_CD	, SUBSTRING(HIRE_YMD, 1, 10) AS HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD = 'CS' OR MCDP_CD = 'GS'
ORDER BY HIRE_YMD DESC, DR_NAME ASC;

// Q20
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);

// Q22
SELECT FLAVOR
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC

// Q33
SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT p
         JOIN OFFLINE_SALE o ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC

